Repository helm/helm-mapkubeapis, pull requests merged in 2022-02, with the labels that each got.

#57 config: add newlines after the k8s kinds
  config/Map.yaml
Labels: bug, size/L

#58 common: print count of replaced api objects
  pkg/common/common.go
  pkg/v2/release.go
  pkg/v3/release.go
Labels: enhancement, size/S

#59 Add migration for storage.k8s.io/v1beta1
  config/Map.yaml
Labels: size/S

#60 chore(release): Cut release 0.2.0
  plugin.yaml
Labels: size/XS
