Repository helm/helm-mapkubeapis, pull requests merged in 2023-03, with the labels that each got.

#98 docs: document how mappings work for the removal scenario
  README.md
Labels: size/S

#100 Fix message
  pkg/common/common.go
Labels: size/S

#99 Bump dependency versions
  go.mod
  go.sum
  pkg/common/common.go
  pkg/common/utils.go
Labels: size/XL

#103 Update plugin version
  plugin.yaml
Labels: size/XS

#102 Update mapping file
  config/Map.yaml
Labels: size/S
